export default {
	products: [
		{
			_id: 1,
			name: "Trio Peppermint",
			category: "Dogs",
			image:
				"https://www.petcircle.com.au/petcircle-assets/images/products/p/tasty-bone-dental-trio-peppermint.png",
			brand: " Tasty Bone",
			price: 27,
			rating: 4.8,
			numReviews: 18,
		},
		{
			_id: 2,
			name: "Doogie",
			category: "Dogs",
			image: "./images/moose.png",
			brand: " Moossie",
			price: 15,
			rating: 5,
			numReviews: 7,
		},
		{
			_id: 3,
			name: "Ball Bounce",
			category: "Dogs",
			image: "./images/ball.png",
			brand: " Kong",
			price: 10,
			rating: 4.5,
			numReviews: 20,
		},
		{
			_id: 4,
			name: "Butterfly",
			category: "Cats",
			image: "./images/butterfly.png",
			brand: " Afp",
			price: 12,
			rating: 4.3,
			numReviews: 9,
		},
		{
			_id: 5,
			name: "FroliCat",
			category: "Cats",
			image: "./images/frolicat.png",
			brand: " Bolt",
			price: 30,
			rating: 4.8,
			numReviews: 12,
		},
		{
			_id: 6,
			name: "KittyFuz",
			category: "Cats",
			image: "./images/kong.png",
			brand: " Kong",
			price: 27,
			rating: 4.8,
			numReviews: 18,
		},
	],
};
